import React from 'react';
import { ShieldCheck, AlertCircle, X, PhoneCall, Stethoscope } from 'lucide-react';

interface MedicalDisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const MedicalDisclaimerModal: React.FC<MedicalDisclaimerModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/50 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2.5 text-slate-900">
            <div className="p-2 bg-cyan-50 rounded-xl text-cyan-600">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold">MediMateAI Medical Disclaimer</h3>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="space-y-3 text-xs text-slate-600 leading-relaxed max-h-96 overflow-y-auto pr-1">
          <div className="p-3 bg-amber-50 rounded-xl border border-amber-200 text-amber-900 flex items-start gap-2.5">
            <AlertCircle className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
            <p>
              <strong>Important Notice:</strong> MediMateAI is an artificial intelligence-assisted health information platform. It is <strong>NOT a doctor</strong> and does <strong>NOT provide clinical medical diagnosis, triage, or prescriptive treatments.</strong>
            </p>
          </div>

          <p>
            1. <strong>Informational & Educational Purpose</strong>: All conversational replies, guidance, and summaries generated by MediMateAI are provided solely for general educational, personal health organization, and preparation for your doctor appointments.
          </p>

          <p>
            2. <strong>Consult Licensed Physicians</strong>: Always consult a qualified medical professional, primary care physician, or licensed specialist regarding any personal medical condition, diagnostic interpretation, or before making changes to any medication regimen.
          </p>

          <p>
            3. <strong>Emergency Protocol</strong>: If you believe you may be experiencing a medical emergency (such as severe chest pain, shortness of breath, sudden numbness, uncontrolled bleeding, or allergic swelling), immediately call <strong>911</strong> or proceed to the nearest emergency room.
          </p>

          <p>
            4. <strong>Data Privacy</strong>: Your personal health entries, medication tracker, and consultations are encrypted and accessible only by you.
          </p>
        </div>

        <div className="pt-2 border-t border-slate-100 flex items-center justify-between gap-3">
          <a
            href="tel:911"
            className="flex items-center gap-1.5 text-xs text-rose-600 hover:text-rose-700 font-semibold"
          >
            <PhoneCall className="w-3.5 h-3.5" />
            Call Emergency (911)
          </a>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold rounded-xl transition-colors"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
};

export const MedicalBanner: React.FC<{ onOpenModal?: () => void }> = ({ onOpenModal }) => {
  return (
    <div className="bg-slate-100/90 border-b border-slate-200/80 px-4 py-1.5 text-[11px] text-slate-600 flex items-center justify-between">
      <div className="flex items-center gap-2 max-w-4xl truncate">
        <Stethoscope className="w-3.5 h-3.5 text-cyan-600 shrink-0" />
        <span className="truncate">
          <strong>Medical Notice:</strong> MediMateAI provides supportive health guidance, not clinical diagnoses. Always verify care with your physician.
        </span>
      </div>
      {onOpenModal && (
        <button
          onClick={onOpenModal}
          className="text-cyan-700 hover:text-cyan-900 font-semibold text-[11px] underline underline-offset-2 ml-3 shrink-0"
        >
          View Full Policy
        </button>
      )}
    </div>
  );
};
